import { describe, expect, test } from "bun:test"
import { bambooCiSkill } from "./bamboo-ci"
import { ciGreenLoopSkill } from "./ci-green-loop"
import { dotnetPlaywrightSkill } from "./dotnet-playwright"

describe("ci green loop builtin skills", () => {
  test("ci-green-loop template requires iteration ledger updates", () => {
    expect(ciGreenLoopSkill.template).toContain(".sisyphus/evidence/repair-log.md")
    expect(ciGreenLoopSkill.template).toContain("Iteration Ledger (MANDATORY)")
    expect(ciGreenLoopSkill.template).toContain("Coverage map:")
    expect(ciGreenLoopSkill.template).toContain("Code changed:")
    expect(ciGreenLoopSkill.template).toContain("Per-test ledger:")
    expect(ciGreenLoopSkill.template).toContain("Checkpoint MUST reference repair-log")
    expect(ciGreenLoopSkill.template).toContain("free-form narrative")
    expect(ciGreenLoopSkill.template).toContain("tracker files with status `fixed-pending`")
    expect(ciGreenLoopSkill.template).toContain("Managed .sisyphus repo fast-path (STRICT)")
    expect(ciGreenLoopSkill.template).toContain("Missing tracker directory is a blocker for code edits")
    expect(ciGreenLoopSkill.template).toContain("If any of those checks fail, DO NOT skip steps (b)-(f)")
    expect(ciGreenLoopSkill.template).toContain("one shared file/helper")
    expect(ciGreenLoopSkill.template).toContain("MATERIALIZE EVIDENCE NOW (hard gate)")
    expect(ciGreenLoopSkill.template).toContain("BEFORE any source-code reads outside `.sisyphus/evidence/`")
    expect(ciGreenLoopSkill.template).toContain("ACTIVE PLAN REBASE (hard gate)")
    expect(ciGreenLoopSkill.template).toContain("Do not carry an old `#315 / 15 fails` Task 2 beside `#317 / 14 fails` evidence")
    expect(ciGreenLoopSkill.template).toContain("Do NOT run extra bookkeeping loops like repeated `wc -c`")
    expect(ciGreenLoopSkill.template).toContain("No partial-failure pushes")
    expect(ciGreenLoopSkill.template).toContain("A push is forbidden if any current failing test appears only in diagnosis text")
    expect(ciGreenLoopSkill.template).toContain("Claude review: PASS | FAIL | BLOCKED")
    expect(ciGreenLoopSkill.template).toContain("A push is forbidden until the current iteration block records `Claude review: PASS`")
    expect(ciGreenLoopSkill.template).toContain("current-iteration fix approach or blocker conclusion")
    expect(ciGreenLoopSkill.template).toContain("staged diff or an explicit reason why no code change was needed")
    expect(ciGreenLoopSkill.template).toContain("The first working response after the live CI fetch is incomplete unless those evidence files were actually modified on disk")
    expect(ciGreenLoopSkill.template).toContain("Do not spend that turn on todo churn, extra plan prose, or adjacent source reads")
    expect(ciGreenLoopSkill.template).toContain("Immediately after evidence materialization, do one full tracker sweep")
    expect(ciGreenLoopSkill.template).toContain("Dirty product files from a prior attempt are never sufficient evidence on their own")
    expect(ciGreenLoopSkill.template).toContain("full failing-set action map from the trackers")
    expect(ciGreenLoopSkill.template).toContain("A 1-2 file batch is invalid if uncovered tests remain")
    expect(ciGreenLoopSkill.template).toContain("Diagnose ALL → Fix ALL → AUDIT → LOCAL TEST → CLAUDE REVIEW → Push ONCE.")
    expect(ciGreenLoopSkill.template).toContain("Mandatory Claude Review")
    expect(ciGreenLoopSkill.template).toContain("Run `review-work` for the exact staged batch")
  })

  test("bamboo-ci template couples Bamboo fetches to repair-log updates", () => {
    expect(bambooCiSkill.template).toContain(".sisyphus/evidence/repair-log.md")
    expect(bambooCiSkill.template).toContain("Every Bamboo iteration must also update")
    expect(bambooCiSkill.template).toContain("build number + revision")
    expect(bambooCiSkill.template).toContain("changed-files coverage")
  })

  test("bamboo-ci template teaches certificate fallback for read-only monitoring", () => {
    expect(bambooCiSkill.template).toContain("curl --insecure")
    expect(bambooCiSkill.template).toContain("Corporate TLS is not a terminal blocker")
    expect(bambooCiSkill.template).toContain("Do NOT stop after a successful push")
    expect(bambooCiSkill.template).toContain("`fetch_json()` is an inline helper function")
    expect(bambooCiSkill.template).toContain("JSON=\"$JSON\" python3 <<'PY'")
    expect(bambooCiSkill.template).toContain("Do NOT build giant one-line commands with nested quotes")
    expect(bambooCiSkill.template).toContain("FORBIDDEN:")
    expect(bambooCiSkill.template).toContain("`python3 -c '...'`")
    expect(bambooCiSkill.template).toContain("raw `curl ... | python3`")
  })

  test("bamboo-ci template requires numbered-build monitoring instead of latest-only polling", () => {
    expect(bambooCiSkill.template).toContain("Poll the branch recent-results feed and the numbered build")
    expect(bambooCiSkill.template).toContain("do NOT rely on it alone")
    expect(bambooCiSkill.template).toContain("A `400 maximum number of concurrent builds allowed` does NOT prove")
    expect(bambooCiSkill.template).toContain("monitor that exact build until terminal state")
  })

  test("ci-green-loop treats Bamboo certificate errors as monitoring fallback, not push failure", () => {
    expect(ciGreenLoopSkill.template).toContain("retry those READ-ONLY fetches with `curl --insecure`")
    expect(ciGreenLoopSkill.template).toContain("That is a CI observation TLS issue, not a push failure")
  })

  test("ci-green-loop evidence eviction preserves repair-log and checkpoint", () => {
    expect(ciGreenLoopSkill.template).toContain('! -name "repair-log.md" ! -name "ci-loop-checkpoint.md"')
    expect(ciGreenLoopSkill.template).toContain("Never delete them just because they exceed 10KB")
    expect(ciGreenLoopSkill.template).toContain("keep test tracker files, repair-log.md, ci-loop-checkpoint.md")
  })

  test("ci-green-loop requires repo-native local test contour bootstrap before skipping verification", () => {
    expect(ciGreenLoopSkill.template).toContain("LOCAL TEST CONTOUR READINESS (hard gate)")
    expect(ciGreenLoopSkill.template).toContain("Search the repo for the documented bootstrap path")
    expect(ciGreenLoopSkill.template).toContain("generated/TestAppInstances.json")
    expect(ciGreenLoopSkill.template).toContain("OPTIEX_PLAYWRIGHT_BASE_URL")
    expect(ciGreenLoopSkill.template).toContain("missing local test contour is SETUP WORK, not a reason to skip verification")
    expect(ciGreenLoopSkill.template).toContain("Missing generated config/env vars\" by itself is NOT enough")
    expect(ciGreenLoopSkill.template).toContain("repo-native bootstrap path")
    expect(ciGreenLoopSkill.template).toContain("every later verify rerun MUST re-export the same required env vars")
    expect(ciGreenLoopSkill.template).toContain("Losing previously provisioned `OPTIEX_PLAYWRIGHT_*`")
    expect(ciGreenLoopSkill.template).toContain("you MUST reuse those values directly for the rerun")
    expect(ciGreenLoopSkill.template).toContain("Do NOT spend another loop rediscovering or reverse-engineering the same env contract")
  })

  test("ci-green-loop allows host-specific full-solution blockers after relevant project build passes", () => {
    expect(ciGreenLoopSkill.template).toContain("Run the narrowest locally runnable build that covers the candidate fix batch")
    expect(ciGreenLoopSkill.template).toContain("If the full solution build fails only because of a host-specific prerequisite unrelated to the edited batch")
    expect(ciGreenLoopSkill.template).toContain("Do NOT pretend this is a product-code failure")
  })

  test("ci-green-loop forbids silent post-push waiting and requires trigger-lag investigation", () => {
    expect(ciGreenLoopSkill.template).toContain("do visible bounded polling of the CI summary at least every 30 seconds")
    expect(ciGreenLoopSkill.template).toContain("If the latest plan/build is still pinned to the previous revision after 2 minutes")
    expect(ciGreenLoopSkill.template).toContain("Silent post-push waiting is forbidden")
    expect(ciGreenLoopSkill.template).toContain("trigger-lag investigation")
  })

  test("ci-green-loop forbids coverage-reducing shortcut fixes and fake passes", () => {
    expect(ciGreenLoopSkill.template).toContain("Coverage integrity is mandatory")
    expect(ciGreenLoopSkill.template).toContain("no fix may reduce end-to-end coverage")
    expect(ciGreenLoopSkill.template).toContain("replace a real UI/API/data path with a stub")
    expect(ciGreenLoopSkill.template).toContain("No Coverage Regression / No Stubbed Passes")
    expect(ciGreenLoopSkill.template).toContain("Do NOT \"fix\" CI by removing assertions")
    expect(ciGreenLoopSkill.template).toContain("partial-chain shortcut or fake green")
  })

  test("dotnet-playwright treats empty waits and idle hangs as a mandatory diagnosis target", () => {
    expect(dotnetPlaywrightSkill.template).toContain("Idle / Empty Wait Failure Mode (MANDATORY)")
    expect(dotnetPlaywrightSkill.template).toContain("A long wait with no meaningful DOM/API state change is a bug")
    expect(dotnetPlaywrightSkill.template).toContain("Always identify the exact awaited signal")
    expect(dotnetPlaywrightSkill.template).toContain("ERR_CONNECTION_REFUSED")
    expect(dotnetPlaywrightSkill.template).toContain("A rerun that times out without a concrete awaited-signal diagnosis is incomplete")
    expect(dotnetPlaywrightSkill.template).toContain("Bounded Rerun Contract (MANDATORY)")
    expect(dotnetPlaywrightSkill.template).toContain("Every local Playwright rerun must be launched through a bounded wrapper")
    expect(dotnetPlaywrightSkill.template).toContain("The bounded wrapper must include a real hard timeout")
    expect(dotnetPlaywrightSkill.template).toContain("the exact results directory and intended TRX path")
    expect(dotnetPlaywrightSkill.template).toContain("declare the expected test count for that rerun")
    expect(dotnetPlaywrightSkill.template).toContain("parse the resulting TRX `UnitTestResult` entries")
    expect(dotnetPlaywrightSkill.template).toContain("TRX shows fewer results than the intended failing-set coverage")
    expect(dotnetPlaywrightSkill.template).toContain("If a rerun lives materially longer than the last comparable local baseline and still has no TRX file")
    expect(dotnetPlaywrightSkill.template).toContain("Do not silently burn more time on an unobservable rerun.")
    expect(dotnetPlaywrightSkill.template).toContain("The rerun command must emit a recurring heartbeat")
    expect(dotnetPlaywrightSkill.template).toContain("RERUN_HEARTBEAT")
    expect(dotnetPlaywrightSkill.template).toContain("stale-runner preflight (`RERUN_PRECHECK`)")
    expect(dotnetPlaywrightSkill.template).toContain("do NOT stack a new rerun on top of it")
    expect(dotnetPlaywrightSkill.template).toContain("still no TRX")
    expect(dotnetPlaywrightSkill.template).toContain("Coverage Integrity (MANDATORY)")
    expect(dotnetPlaywrightSkill.template).toContain("Do NOT replace a real UI/API/data-path validation with a stub")
    expect(dotnetPlaywrightSkill.template).toContain("Do NOT turn a failing full-chain Playwright test into a helper-only shortcut")
    expect(dotnetPlaywrightSkill.template).toContain("Do NOT bypass the awaited UI/API/backend path just to get CI green")
  })
})
